# jamobegbie/django.nv/.github/actions/snyk-action/action.yml
name: 'Snyk Action'
description: 'Run Snyk checks'
inputs:
  snyk-token:
    description: 'Snyk authentication token'
    required: true
runs:
  using: composite
  steps:
    - name: Run Snyk
      run: |
        echo ${{ inputs.snyk-token }} | snyk auth --stdin
        snyk test --json
      shell: bash

      
