name: Auth Snyk

inputs:
  snyk-token:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name:  Snyk auth
      run: |
        echo ${{ inputs.snyk-token }} | snyk auth --stdin
      
