name: Setup Respository Secrets

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      GCP_CREDENTIALS:
         required: true
      PROJECT_ID:
         required: true
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: add secrets
        run: |
          gh secret set "Test_Snyk_API" --body "${{ "testing" }}" --repo jamobegbie/${{ inputs.repository }}
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
