name: Snyk

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sast
      uses: snyk/actions/python@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN  }}
        ORG_ID: e5d6cf84-a29f-42ed-b73a-731d727d8853
      with:
        command: code
