name: Snyk

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SCA
      uses: snyk/actions/python@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN  }}
        ORG_ID: e5d6cf84-a29f-42ed-b73a-731d727d8853
      with:
        args: --sarif-file-output=test.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: test.sarif
  SAST:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sast
      uses: snyk/actions/maven@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN  }}
      with:
        args: --sarif-file-output=code.sarif
        command: code test --json > sast_output.json
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: code.sarif
    - name: Store results to JSON
      uses: actions/upload-artifact@v2
      with:
        name: sast-json-output
        path: sast_output.json
